export type NodeCategory =
  | "company"
  | "department"
  | "workflow"
  | "process"
  | "automation"
  | "human"
  | "output"
  | "ambient";

export interface NodeTooltip {
  title: string;
  items: string[];
  cta: string;
  href?: string;
}

export interface CoreNodeDef {
  id: string;
  label: string;
  category: NodeCategory;
  treeX: number;
  treeY: number;
  chaosX: number;
  chaosY: number;
  depth: number;
  size: number;
  tooltip?: NodeTooltip;
}

export const SIGNATURE_PATH = [
  "business",
  "operations",
  "orders",
  "classify",
  "automation",
  "human",
  "action",
] as const;

export const CORE_NODES: CoreNodeDef[] = [
  {
    id: "business",
    label: "BUSINESS",
    category: "company",
    treeX: 0.72,
    treeY: 0.16,
    chaosX: 0.5,
    chaosY: 0.22,
    depth: 0.2,
    size: 7.5,
  },
  {
    id: "sales",
    label: "SALES",
    category: "department",
    treeX: 0.52,
    treeY: 0.3,
    chaosX: 0.22,
    chaosY: 0.18,
    depth: 0.35,
    size: 5.2,
  },
  {
    id: "operations",
    label: "OPERATIONS",
    category: "department",
    treeX: 0.72,
    treeY: 0.3,
    chaosX: 0.7,
    chaosY: 0.42,
    depth: 0.25,
    size: 5.4,
  },
  {
    id: "support",
    label: "SUPPORT",
    category: "department",
    treeX: 0.88,
    treeY: 0.3,
    chaosX: 0.9,
    chaosY: 0.16,
    depth: 0.4,
    size: 5.2,
  },
  {
    id: "finance",
    label: "FINANCE",
    category: "department",
    treeX: 0.42,
    treeY: 0.42,
    chaosX: 0.18,
    chaosY: 0.55,
    depth: 0.5,
    size: 4.8,
  },
  {
    id: "logistics",
    label: "LOGISTICS",
    category: "department",
    treeX: 0.92,
    treeY: 0.44,
    chaosX: 0.94,
    chaosY: 0.62,
    depth: 0.45,
    size: 4.8,
  },
  {
    id: "leads",
    label: "LEADS",
    category: "workflow",
    treeX: 0.5,
    treeY: 0.44,
    chaosX: 0.12,
    chaosY: 0.34,
    depth: 0.4,
    size: 4.4,
  },
  {
    id: "orders",
    label: "ORDERS",
    category: "workflow",
    treeX: 0.72,
    treeY: 0.44,
    chaosX: 0.58,
    chaosY: 0.72,
    depth: 0.3,
    size: 4.6,
    tooltip: {
      title: "ORDER OPERATIONS",
      items: ["Completed", "Delayed", "Refund request", "Cancellation", "Complaint"],
      cta: "Explore workflow →",
      href: "#solutions",
    },
  },
  {
    id: "emails",
    label: "EMAIL",
    category: "workflow",
    treeX: 0.88,
    treeY: 0.44,
    chaosX: 0.34,
    chaosY: 0.12,
    depth: 0.38,
    size: 4.6,
    tooltip: {
      title: "EMAIL OPERATIONS",
      items: ["Classified", "Routed", "Summarized", "Responded to", "Escalated"],
      cta: "Automate this workflow →",
      href: "#contact",
    },
  },
  {
    id: "invoices",
    label: "INVOICES",
    category: "workflow",
    treeX: 0.4,
    treeY: 0.56,
    chaosX: 0.08,
    chaosY: 0.7,
    depth: 0.55,
    size: 4.3,
  },
  {
    id: "documents",
    label: "DOCUMENTS",
    category: "workflow",
    treeX: 0.58,
    treeY: 0.56,
    chaosX: 0.28,
    chaosY: 0.82,
    depth: 0.48,
    size: 4.4,
    tooltip: {
      title: "DOCUMENT AUTOMATION",
      items: ["Extract data", "Validate", "Enter into system", "Request approval"],
      cta: "Explore workflow →",
      href: "#solutions",
    },
  },
  {
    id: "customers",
    label: "CUSTOMERS",
    category: "workflow",
    treeX: 0.84,
    treeY: 0.56,
    chaosX: 0.96,
    chaosY: 0.78,
    depth: 0.5,
    size: 4.3,
  },
  {
    id: "qualify",
    label: "QUALIFY",
    category: "process",
    treeX: 0.5,
    treeY: 0.56,
    chaosX: 0.16,
    chaosY: 0.48,
    depth: 0.42,
    size: 3.8,
  },
  {
    id: "classify",
    label: "CLASSIFY",
    category: "process",
    treeX: 0.72,
    treeY: 0.56,
    chaosX: 0.64,
    chaosY: 0.88,
    depth: 0.32,
    size: 4,
  },
  {
    id: "extract",
    label: "EXTRACT",
    category: "process",
    treeX: 0.58,
    treeY: 0.66,
    chaosX: 0.4,
    chaosY: 0.9,
    depth: 0.5,
    size: 3.8,
  },
  {
    id: "verify",
    label: "VERIFY",
    category: "process",
    treeX: 0.42,
    treeY: 0.68,
    chaosX: 0.2,
    chaosY: 0.92,
    depth: 0.58,
    size: 3.6,
  },
  {
    id: "route",
    label: "ROUTE",
    category: "process",
    treeX: 0.86,
    treeY: 0.66,
    chaosX: 0.98,
    chaosY: 0.4,
    depth: 0.46,
    size: 3.6,
  },
  {
    id: "update",
    label: "UPDATE",
    category: "process",
    treeX: 0.64,
    treeY: 0.72,
    chaosX: 0.48,
    chaosY: 0.96,
    depth: 0.52,
    size: 3.6,
  },
  {
    id: "respond",
    label: "RESPOND",
    category: "process",
    treeX: 0.9,
    treeY: 0.72,
    chaosX: 0.86,
    chaosY: 0.92,
    depth: 0.55,
    size: 3.6,
  },
  {
    id: "automation",
    label: "AI AUTOMATION",
    category: "automation",
    treeX: 0.72,
    treeY: 0.7,
    chaosX: 0.54,
    chaosY: 0.58,
    depth: 0.22,
    size: 6.4,
  },
  {
    id: "human",
    label: "HUMAN APPROVAL",
    category: "human",
    treeX: 0.72,
    treeY: 0.82,
    chaosX: 0.78,
    chaosY: 0.96,
    depth: 0.28,
    size: 5.6,
  },
  {
    id: "action",
    label: "ACTION",
    category: "output",
    treeX: 0.72,
    treeY: 0.92,
    chaosX: 0.62,
    chaosY: 0.98,
    depth: 0.3,
    size: 5,
  },
  {
    id: "crm",
    label: "CRM UPDATED",
    category: "output",
    treeX: 0.56,
    treeY: 0.9,
    chaosX: 0.3,
    chaosY: 0.98,
    depth: 0.6,
    size: 3.8,
  },
  {
    id: "notified",
    label: "CUSTOMER NOTIFIED",
    category: "output",
    treeX: 0.84,
    treeY: 0.9,
    chaosX: 0.92,
    chaosY: 0.98,
    depth: 0.58,
    size: 3.8,
  },
  {
    id: "report",
    label: "REPORT GENERATED",
    category: "output",
    treeX: 0.46,
    treeY: 0.84,
    chaosX: 0.1,
    chaosY: 0.86,
    depth: 0.62,
    size: 3.6,
  },
  {
    id: "task",
    label: "TASK CREATED",
    category: "output",
    treeX: 0.9,
    treeY: 0.84,
    chaosX: 0.98,
    chaosY: 0.88,
    depth: 0.6,
    size: 3.6,
  },
];

export const CORE_EDGES: [string, string][] = [
  ["business", "sales"],
  ["business", "operations"],
  ["business", "support"],
  ["business", "finance"],
  ["business", "logistics"],
  ["sales", "leads"],
  ["leads", "qualify"],
  ["qualify", "automation"],
  ["operations", "orders"],
  ["orders", "classify"],
  ["classify", "automation"],
  ["support", "emails"],
  ["emails", "route"],
  ["finance", "invoices"],
  ["invoices", "extract"],
  ["extract", "verify"],
  ["operations", "documents"],
  ["documents", "extract"],
  ["support", "customers"],
  ["customers", "respond"],
  ["logistics", "orders"],
  ["route", "automation"],
  ["verify", "automation"],
  ["update", "automation"],
  ["respond", "automation"],
  ["automation", "human"],
  ["human", "action"],
  ["action", "crm"],
  ["action", "notified"],
  ["action", "report"],
  ["action", "task"],
  ["qualify", "crm"],
  ["update", "crm"],
];

export const HOW_STEP_FOCUS: Record<number, Array<NodeCategory | string>> = {
  1: ["department", "company"],
  2: ["workflow"],
  3: ["process"],
  4: ["automation"],
  5: ["output", "human"],
};

export const MOBILE_CORE_IDS = [
  "business",
  "operations",
  "support",
  "orders",
  "emails",
  "documents",
  "classify",
  "automation",
  "human",
  "action",
];
